spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:docketcartorios
    driverClassName: org.h2.Driver  
    username: sa  
    password:
  h2:
    console:
      enabled: true
      path: /cartorios_db

server.port: 8081